version: '3.7'

services:
  base:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_base
    image: etable/php:base
  
  develop:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_develop
    image: etable/php:dev-n-build
    volumes:
      - "nginx-php:/var/www/html"
    links: 
      - base
      - memcache
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - 7080:7080
    links:
      - "develop:develop"
    volumes:
      - "nginx-php:/var/www/html"
      - "./dist/nginx.conf:/etc/nginx/nginx.conf:ro"
  
  memcache:
    image: memcached:alpine
  
  redis:
    image: redis:alpine

volumes:
  nginx-php: 
     driver: local
     driver_opts:
      o: bind
      type: none
      device: ${CODE_BASE_PATH}
