version: '3'

services:
  base:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_base
    image: etable/php:base
  
  develop:
    build:
      context: .
      dockerfile: ./dockerfiles/
    image: etable/php:dev-n-build
    links: 
      - base